// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcrf4agBaGYnffY_lHnerjf4Ap62sxN74',
    appId: '1:782740288046:web:031142876d6df8567ce5bf',
    messagingSenderId: '782740288046',
    projectId: 'flutter-crud-firebase-51e6a',
    authDomain: 'flutter-crud-firebase-51e6a.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-51e6a.firebasestorage.app',
    measurementId: 'G-18FM7R07JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-X983HdUV6_Th8iLWZUC6ES40F4Gvw3Y',
    appId: '1:782740288046:android:f56ba115a0fbd4117ce5bf',
    messagingSenderId: '782740288046',
    projectId: 'flutter-crud-firebase-51e6a',
    storageBucket: 'flutter-crud-firebase-51e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3kbzLNkOjFGM4emu151FmbjrPewfGNyc',
    appId: '1:782740288046:ios:32df643451ee74267ce5bf',
    messagingSenderId: '782740288046',
    projectId: 'flutter-crud-firebase-51e6a',
    storageBucket: 'flutter-crud-firebase-51e6a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3kbzLNkOjFGM4emu151FmbjrPewfGNyc',
    appId: '1:782740288046:ios:32df643451ee74267ce5bf',
    messagingSenderId: '782740288046',
    projectId: 'flutter-crud-firebase-51e6a',
    storageBucket: 'flutter-crud-firebase-51e6a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcrf4agBaGYnffY_lHnerjf4Ap62sxN74',
    appId: '1:782740288046:web:102cf13b47fda50f7ce5bf',
    messagingSenderId: '782740288046',
    projectId: 'flutter-crud-firebase-51e6a',
    authDomain: 'flutter-crud-firebase-51e6a.firebaseapp.com',
    storageBucket: 'flutter-crud-firebase-51e6a.firebasestorage.app',
    measurementId: 'G-HQ2DF09Z2S',
  );
}
